/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'markovich' at '4/28/17 1:33 PM' with Gradle 2.10
 *
 * @author markovich, @date 4/28/17 1:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
